# Generated by Django 2.1 on 2018-09-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_auto_20180920_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='Interest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
