# Generated by Django 2.1 on 2018-09-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0003_auto_20180920_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='Interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
