# Generated by Django 2.1 on 2018-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0004_auto_20180920_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='Interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
