# Generated by Django 2.1 on 2018-09-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0005_auto_20180920_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='Interest',
            new_name='interest',
        ),
    ]
