# Generated by Django 2.1 on 2018-09-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0006_auto_20180920_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
    ]
