# Generated by Django 2.1 on 2018-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0009_auto_20180921_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
