# Generated by Django 2.1 on 2018-09-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0010_auto_20180922_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='ret_date',
            new_name='date',
        ),
    ]
