# Generated by Django 2.1 on 2018-09-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0011_auto_20180922_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='amount',
            new_name='Initial_amount',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='interest',
        ),
        migrations.AddField(
            model_name='borrower',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='rec_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
