# Generated by Django 2.1 on 2018-09-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0012_auto_20180924_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='borrow',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
    ]
