# Generated by Django 2.1 on 2018-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0014_auto_20180924_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='terms',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
