# Generated by Django 2.1 on 2018-09-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0015_borrower_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='borrow',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
    ]
