# Generated by Django 2.1 on 2018-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0019_auto_20180926_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='interest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
