# Generated by Django 2.1 on 2018-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0020_auto_20180926_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='intamt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
