# Generated by Django 2.1 on 2018-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0022_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
