# Generated by Django 2.1 on 2018-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0025_auto_20180930_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='terms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
