# Generated by Django 2.1 on 2018-10-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0027_auto_20181004_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lender',
            old_name='Initial_amount',
            new_name='initial_amount',
        ),
    ]
