# Generated by Django 2.1 on 2018-10-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0028_auto_20181004_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='borrow',
            new_name='lender',
        ),
    ]
