# Generated by Django 2.1 on 2018-10-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0032_auto_20181015_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='lender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transact.Lender'),
        ),
    ]
