# Generated by Django 2.1 on 2018-10-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0035_auto_20181015_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='lender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
